@echo off
echo Stopping any existing Python processes...
taskkill /f /im python.exe 2>nul
taskkill /f /im pythonw.exe 2>nul
echo Waiting 3 seconds for processes to stop...
timeout /t 3 /nobreak >nul
echo Starting Giglio Download Bot...
python run.py
pause